# Generated by Django 3.2.9 on 2021-12-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211126_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('name',), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='teamimage',
            options={'ordering': ('image',), 'verbose_name': 'Фото для истории', 'verbose_name_plural': 'Фото для истории'},
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Описание'),
        ),
    ]
