# Generated by Django 3.2.9 on 2021-12-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20211206_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Driverl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DriverR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='rank',
        ),
        migrations.AlterModelOptions(
            name='teamimage',
            options={'ordering': ('image',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RemoveField(
            model_name='teamimage',
            name='team',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='teamimage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.car'),
        ),
        migrations.AddField(
            model_name='teamimage',
            name='driverL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.driverl'),
        ),
        migrations.AddField(
            model_name='teamimage',
            name='driverR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.driverr'),
        ),
    ]
