# Generated by Django 3.2.9 on 2021-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20211212_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.RemoveField(
            model_name='driverl',
            name='description',
        ),
        migrations.RemoveField(
            model_name='driverl',
            name='title',
        ),
        migrations.RemoveField(
            model_name='driverr',
            name='description',
        ),
        migrations.RemoveField(
            model_name='driverr',
            name='title',
        ),
        migrations.AlterField(
            model_name='car',
            name='text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='driverl',
            name='text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='driverr',
            name='text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
