# Generated by Django 3.2.9 on 2021-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(db_index=True, max_length=200, verbose_name='Гонщик')),
                ('team', models.CharField(db_index=True, max_length=200, verbose_name='Команда')),
                ('point', models.CharField(db_index=True, max_length=200, verbose_name='Очки')),
                ('country', models.CharField(db_index=True, max_length=200, verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Личный зачет',
                'verbose_name_plural': 'Личный зачет',
                'ordering': ('driver',),
            },
        ),
        migrations.CreateModel(
            name='team_standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(db_index=True, max_length=200, verbose_name='Команда')),
                ('point', models.CharField(db_index=True, max_length=200, verbose_name='Очки')),
                ('country', models.CharField(db_index=True, max_length=200, verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Кубок Конструкторов',
                'verbose_name_plural': 'Кубок Конструкторов',
                'ordering': ('team',),
            },
        ),
    ]
