# Generated by Django 3.2.9 on 2021-11-26 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_and_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(db_index=True, max_length=200, verbose_name='Команда')),
                ('country', models.CharField(db_index=True, max_length=200, verbose_name='Страны')),
            ],
        ),
        migrations.AlterModelOptions(
            name='team_standing',
            options={},
        ),
        migrations.RemoveField(
            model_name='personal_standing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personal_standing',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team_standing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='team_standing',
            name='team',
        ),
        migrations.AddField(
            model_name='personal_standing',
            name='country_and_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.country_and_team'),
        ),
        migrations.AddField(
            model_name='team_standing',
            name='country_and_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.country_and_team'),
        ),
    ]
