# Generated by Django 3.2.9 on 2021-11-26 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0002_auto_20211126_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=200, verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Личный зачет',
                'verbose_name_plural': 'Личный зачет',
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(db_index=True, max_length=200, verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Личный зачет',
                'verbose_name_plural': 'Личный зачет',
                'ordering': ('team',),
            },
        ),
        migrations.RemoveField(
            model_name='personal_standing',
            name='country_and_team',
        ),
        migrations.RemoveField(
            model_name='team_standing',
            name='country_and_team',
        ),
        migrations.DeleteModel(
            name='country_and_team',
        ),
        migrations.AddField(
            model_name='personal_standing',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.country'),
        ),
        migrations.AddField(
            model_name='personal_standing',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.team'),
        ),
        migrations.AddField(
            model_name='team_standing',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.country'),
        ),
        migrations.AddField(
            model_name='team_standing',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.team'),
        ),
    ]
