# Generated by Django 3.2.9 on 2021-11-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_auto_20211126_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_standing',
            options={'ordering': ('point',), 'verbose_name': 'Личный зачет', 'verbose_name_plural': 'Личный зачет'},
        ),
    ]
