# Generated by Django 3.2.9 on 2021-12-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0004_alter_team_standing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',), 'verbose_name': 'Страна', 'verbose_name_plural': 'Страна'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('team',), 'verbose_name': 'Команда', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='team_standing',
            options={'ordering': ('point',), 'verbose_name': 'Командный зачет', 'verbose_name_plural': 'Командный зачет'},
        ),
    ]
