# Generated by Django 3.2.9 on 2021-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0005_auto_20211206_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_standing',
            options={'ordering': ('team',), 'verbose_name': 'Командный зачет', 'verbose_name_plural': 'Командный зачет'},
        ),
        migrations.RenameField(
            model_name='team_standing',
            old_name='point',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='personal_standing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='team_standing',
            name='country',
        ),
        migrations.AlterField(
            model_name='personal_standing',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_standing',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
