# Generated by Django 3.2.9 on 2021-12-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0006_auto_20211215_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal_standing',
            options={'ordering': ('-point',), 'verbose_name': 'Личный зачет', 'verbose_name_plural': 'Личный зачет'},
        ),
        migrations.AlterModelOptions(
            name='team_standing',
            options={'ordering': ('score',), 'verbose_name': 'Командный зачет', 'verbose_name_plural': 'Командный зачет'},
        ),
        migrations.AlterField(
            model_name='personal_standing',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team_standing',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Команда'),
        ),
    ]
