# Generated by Django 3.2.9 on 2022-02-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0008_alter_personal_standing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_standing',
            options={'ordering': ('point1',), 'verbose_name': 'Командный зачет', 'verbose_name_plural': 'Командный зачет'},
        ),
        migrations.RenameField(
            model_name='team_standing',
            old_name='score',
            new_name='point1',
        ),
    ]
