# Generated by Django 3.2.9 on 2022-02-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0009_auto_20220203_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='Команда')),
                ('driver', models.CharField(db_index=True, max_length=200, verbose_name='Гонщик')),
                ('point', models.IntegerField(db_index=True, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Личный зачет',
                'verbose_name_plural': 'Личный зачет',
                'ordering': ('point',),
            },
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='Команда')),
                ('score', models.IntegerField(db_index=True, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Командный зачет',
                'verbose_name_plural': 'Командный зачет',
                'ordering': ('score',),
            },
        ),
        migrations.DeleteModel(
            name='personal_standing',
        ),
        migrations.DeleteModel(
            name='team_standing',
        ),
    ]
