# Generated by Django 3.2.9 on 2022-02-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0010_auto_20220214_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalstanding',
            name='point',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='teamstanding',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=3, verbose_name='Очки'),
        ),
    ]
