# Generated by Django 3.2.9 on 2022-02-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0011_auto_20220215_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalstanding',
            options={'ordering': ('driver',), 'verbose_name': 'Личный зачет', 'verbose_name_plural': 'Личный зачет'},
        ),
        migrations.AlterModelOptions(
            name='teamstanding',
            options={'ordering': ('team',), 'verbose_name': 'Командный зачет', 'verbose_name_plural': 'Командный зачет'},
        ),
        migrations.AlterField(
            model_name='personalstanding',
            name='point',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=4, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='teamstanding',
            name='score',
            field=models.DecimalField(db_index=True, decimal_places=1, max_digits=4, verbose_name='Очки'),
        ),
    ]
