# Generated by Django 3.2.9 on 2022-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('Published', 'Опубликован'), ('Unpublished', 'Не опубликован')], default='опубликован', max_length=30, verbose_name='Статус'),
        ),
    ]
