# Generated by Django 3.2.8 on 2021-10-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('image',), 'verbose_name': 'Фото для истории'},
        ),
    ]
