# Generated by Django 3.2.9 on 2021-12-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211221_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_category',
            new_name='subcategory',
        ),
    ]
