# Generated by Django 3.2.9 on 2021-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_parent_category_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='Subcategory',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Subcategory'),
        ),
    ]
