# Generated by Django 3.2.9 on 2021-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211222_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Subcategory',
            field=models.ManyToManyField(blank=True, to='shop.Subcategory'),
        ),
    ]
