# Generated by Django 3.2.9 on 2022-01-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
