# Generated by Django 3.2.9 on 2022-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Мужчинам'), ('Women', 'Женщинам'), ('Children', 'Детям'), ('Souvenirs', 'Сувениры')], default='male', max_length=20),
        ),
    ]
