# Generated by Django 3.2.9 on 2021-11-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('slug', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'История',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Период',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HistoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='history')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='history.history')),
            ],
            options={
                'verbose_name': 'Фото для истории',
                'ordering': ('image',),
            },
        ),
        migrations.AddField(
            model_name='history',
            name='Year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.year'),
        ),
    ]
