# Generated by Django 3.2.9 on 2021-11-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('title',), 'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='historyimage',
            options={'ordering': ('image',), 'verbose_name': 'Фото для истории', 'verbose_name_plural': 'Фото для истории'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('name',), 'verbose_name': 'Период', 'verbose_name_plural': 'Период'},
        ),
    ]
