# Generated by Django 3.2.9 on 2021-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=10, verbose_name='Дата')),
                ('image', models.ImageField(blank=True, upload_to='schedule/%Y/%m/%d', verbose_name='Фото')),
                ('grandprix', models.CharField(db_index=True, max_length=200, verbose_name='Гран При')),
                ('track', models.CharField(db_index=True, max_length=200, verbose_name='Трасса')),
                ('length', models.CharField(max_length=10, verbose_name='Длина')),
                ('laps', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Круги')),
                ('distance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Дистанция')),
                ('winner', models.CharField(db_index=True, max_length=200, verbose_name='Победитель')),
                ('team', models.CharField(db_index=True, max_length=200, verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календарь',
                'ordering': ('grandprix',),
            },
        ),
    ]
