# Generated by Django 3.2.9 on 2022-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='laps',
            field=models.IntegerField(verbose_name='Круги'),
        ),
    ]
