# Generated by Django 3.2.9 on 2021-11-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autontification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
