# Generated by Django 3.2.9 on 2022-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autontification', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
